pr:
- master

pool:
    vmImage: 'macOS 10.14'

steps:
- bash: ./xnubuild.sh -travis -compress_roots -separate_libsyscall
  displayName: Run xnubuild.sh
  continueOnError: false
- task: CopyFiles@2
  displayName: Copy Build Outputs
  inputs:
    SourceFolder: $(Build.SourceDirectory)/build/roots
    Contents: '*.tar.gz'
    TargetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'roots'
    publishLocation: 'Container'
